### ISSUE TITLE
Couldn't start Fasta reference workflow

### ISSUE THREAD

**Issue by youssefabadir** [nanoporetech/epi2me-api#2]
```typescript
router.post('/fastqref', function (req, res, next) {
  const EPI2ME = new API({
    url: 'https://epi2me.nanoporetech.com',
    apikey: 'apikeyhere',
    apisecret: 'secretkeyhere',
    inputFolder: req.body['inputFolder'],
    outputFolder: req.body['outputFolder'],
  });

  const factory = new Factory(API);
  const workflowId = 1825;
  EPI2ME.REST.startWorkflow({ variables: { idWorkflowInstance: workflowId }})
  .then(console.info)
  .catch(console.error);
```

Error is attached below.
![Capture](https://user-images.githubusercontent.com/35773237/96879507-6cdf3600-147c-11eb-8e94-f6e0e3af35db.PNG)

**Comment by glenveegee** [comment]
Hi @youssefabadir, 

Could you please confirm which version on the epi2me API you are currently working with. We release a version recently that has a number of breaking changes so we'd just like to confirm whether it's that version or an older one.

**Comment by glenveegee** [comment]
If everything else is correct it should be a simple case of renaming the variable that you pass to the startWorkflow method as follows:

```javascript

EPI2ME.REST.startWorkflow({id_workflow: workflowId })

```

**Comment by youssefabadir** [comment]
I'm currently using  v3.0.1623. if there is an updated, how can I install it?

**Comment by glenveegee** [comment]
The last stable release of the EPI2ME API was released in June. 

If you'd like to install that version you can run the following:
```sh
npm i @metrichor/epi2me-api@latest
```

The new version that I was referring to above is still in beta and we are still in the process of updating the documentation. It is written in Typescript and is fully typed so that might work well for you despite the lack of documentation if you're using it in a TS project.

If you'd like to try that version out then you can install it as follows:

```sh
npm i @metrichor/epi2me-api@next
```

**Comment by glenveegee** [comment]
Has the change suggested above regarding `startWorkflow` arguments fixed your original issue?

**Comment by youssefabadir** [comment]
Yea, the suggest about `startworkflow`  fixed the problem. I tried

`npm i @metrichor/epi2me-api@latest`

and it gave me this error:

![Capture](https://user-images.githubusercontent.com/35773237/97006980-f6f0d280-1540-11eb-9c02-0dcafa5e620c.PNG)

**Comment by youssefabadir** [comment]
Also, I tried 

`npm i @metrichor/epi2me-api@next`

It give me status code 500. 
Can you tell me which version to use and what is the syntax of that version?

**Comment by glenveegee** [comment]
If you want to try the `next` brach you're code is going to look something like this...

```javascript
var {EPI2ME, Factory, Profile} = require('@metrichor/epi2me-api');

const profileName = process.argv[2]; // PULL OUT CREDENTIALS FROM EPI2ME PROFILES  FILE
const profile = new Profile().profile(profileName);

const api = new Factory(EPI2ME, profile);

api.graphQL
  .workflows({variables: {pageSize: 5, orderBy: '-idWorkflow', isActive: 1}})
  .then(workflows => {
    const { data: { allWorkflows }} = workflows
    console.info( JSON.stringify(allWorkflows, null, 2 ))
  })
  .catch(console.error);

api.graphQL
  .user()
  .then(async user => {
    const [_, {idUserAccount: computeAccountId}] = user.data.me.useraccountSet;
    const idWorkflow = 1825;

    runningInstance = await api.startGQLRun(
      { inputFolders: ['/private/tmp/apitest/foo'], outputFolder: '/private/tmp/apitest/bar' },
      { idWorkflow, isConsentedHuman: false, computeAccountId },
    );
    console.info('RUNNING INSTANCE', runningInstance)
    runningInstance.liveStates$.subscribe(instanceState => {
      console.info('LIVE INSTANCE STATE', instanceState)
    })

  })
  .catch(console.error);

```

**Comment by glenveegee** [comment]
The `profile` argument given to the Factory is just an object containing apikey and apisecret e.g:

```
{
    apikey: 'apikeyhere',
    apisecret: 'secretkeyhere',
}
```

**Comment by glenveegee** [comment]
@youssefabadir Please let us know if the suggestion above has resolved the issue of connecting to and starting analysis in  EPI2ME

**Comment by youssefabadir** [comment]
It started the analysis but we have an issue with uploading the files.

`LIVE INSTANCE STATE {
  download: {
    progress: { bytes: 0, total: 0, niceSize: 0 },
    success: { files: 0, bytes: 0, reads: 0, niceReads: 0, niceSize: 0 },
    types: {},
    fail: 0,
    niceTypes: ''
  },
  upload: {
    progress: { bytes: -8655034949, total: 0, niceSize: '-8655034949' },
    success: { files: 0, bytes: 0, reads: 0, niceReads: '0', niceSize: '0' },
    types: {},
    filesCount: 29,
    niceTypes: '',
    failure: { 'NoSuchBucket: The specified bucket does not exist': 28 }
  },
  warnings: []
}`

When we try to upload files, it give the above error. Can you help us with how to specify the files to the api?

**Comment by glenveegee** [comment]
Continued in https://github.com/nanoporetech/epi2me-api/issues/3
