### ISSUE TITLE
epi2me-agent3-promethion (Ubuntu)

### ISSUE THREAD

**Issue by AmhedVargas** [nanoporetech/epi2me-api#35]
Apologies but I didn't find the right place to mention an error I obtained when trying to install the agent for epitome service as described in:

https://community.nanoporetech.com/docs/prepare/library_prep_protocols/epi2me/v/mte_1014_v1_revca_11apr2016/installing-the-desktop-age-50426

It seems the newest version (3.4.1-5831769) gives an error  installation (or updating for that matter) in ubuntu., e.g.:
 sudo apt-get install epi2me-agent3-promethion
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  epi2me-agent3-promethion
0 upgraded, 1 newly installed, 0 to remove and 57 not upgraded.
Need to get 80.8 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://cdn.oxfordnanoportal.com/apt focal-stable/non-free amd64 epi2me-agent3-promethion all 3.4.1-5831769 [80.8 MB]
Fetched 80.8 MB in 6s (13.1 MB/s)
Selecting previously unselected package epi2me-agent3-promethion.
(Reading database ... 398624 files and directories currently installed.)
Preparing to unpack .../epi2me-agent3-promethion_3.4.1-5831769_all.deb ...
Unpacking epi2me-agent3-promethion (3.4.1-5831769) ...
Setting up epi2me-agent3-promethion (3.4.1-5831769) ...
id: ‘grid’: no such user
id: ‘prom’: no such user
chown: invalid user: ‘dummy’
chown: invalid user: ‘dummy’
chgrp: invalid group: ‘dummy’
Migrating Agent data out of $home into /data
ln: failed to create symbolic link '~dummy/.epi2me': No such file or directory
chown: invalid user: ‘dummy’
chgrp: invalid group: ‘dummy’
dpkg: error processing package epi2me-agent3-promethion (--configure):
 installed epi2me-agent3-promethion package post-installation script subprocess returned error exit status 1
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Errors were encountered while processing:
 epi2me-agent3-promethion
E: Sub-process /usr/bin/dpkg returned an error code (1)

In my opinon, the subprocess of installation (through dpkg) assumes that the system have two users called grid and prom and even a group called dummy.  

Anyway, is this the right place to report this error? Otherwise, could you please point me to the right place?

Thank you!

Amhed

**Comment by shortercode** [comment]
Hi @AmhedVargas can I confirm if you are actually running on a PromethION? That deb is intended for a specific piece of ONT hardware.

Also I should note that EPI2ME classic platform is due to be retired soon please take a look at https://labs.epi2me.io/agent-transition/ for information on the migration to the new platform.

**Comment by AmhedVargas** [comment]
Hey,

Thank you so much for so prompt response. I didnt know about the transition.

Also, correct, we acquired a PromethION P2 solo. Is the epi2me-agent3-promethion the correct software to use? 

Thanks again and apologies for using this repo as means to enquiry about my issue.

**Comment by AmhedVargas** [comment]
My bad, just noticed that I was supposed to use just the agent3. Totally bad and apologies

**Comment by shortercode** [comment]
No problem, I've made a note that we should put a note about the migration on this repo. We've also had a few support cases coming here recently for some reason. Perhaps a change to the support page, I'm not sure.

If you have any further issues please direct your queries via https://nanoporetech.com/support/ or [support@nanoporetech.com](mailto:support@nanoporetech.com) who should be able to help you better.
